#edad = int(input("Ingrese su edad: "))
#print("Tu edad es:", edad)
#=============FORMULARIO================
print ("FORMULARIO DE USUARIOS")
nombre = input("Ingrese su nombre número uno")

nombre2 = input("Ingrese su nombre numero dos")
apellido = input("Ingrese su apellido")
apellido2 = input("Ingrese su apellido dos")
print ("el nombre completo es",nombre + " " + nombre2 + " " + apellido + " " +apellido2)
#=================DATOS NUMERICOS====================
edad = int(input("ingrese su" ))
peso = float(input("ingrese su peso"))
telefono =int(input("ingrese su telefono"))
altura =float(input("ingrese su altura"))
hijos =int(input("ingrese el numero de hiios"))
año_nacimiento =int(input("ingrese su año de nacimiento"))
mes_nacimiento =int(input("ingrese su mes de nacimiento"))
dia_nacimiento =int(input("ingrese su añdia de nacimiento"))
cedula = int(input("ingrese su numero de cedula"))
#=====================0DATOS TEXTO O STRING============
correo = input ("ingrese su correo")
tipo_sangre = input ("ingrese su tipo de sangre")
genero = input ("ingrese su genero")
estado = input ("ingrese si es casado o soltero")
eps = input ("ingrese su eps")
universidad = input (" ingrese su universidad")
carrera = input ("ingrese su carrera")
print( nombre, apellido, edad, peso, telefono, altura, hijos, año_nacimiento, mes_nacimiento, dia_nacimiento, cedula, correo,)